# Generated by Django 2.2 on 2020-06-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0004_book_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
