# Generated by Django 2.2 on 2019-08-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active',
        ),
        migrations.AddField(
            model_name='post',
            name='slo',
            field=models.IntegerField(default=119),
        ),
    ]
