# Generated by Django 2.2 on 2019-08-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190827_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slo',
        ),
    ]
