# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-08 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('pcost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pcolor', models.CharField(default='black', max_length=20)),
                ('pmfd', models.DateTimeField(default=datetime.datetime(2018, 9, 8, 17, 12, 12, 453299))),
                ('pexd', models.DateTimeField(default=datetime.datetime(2020, 9, 7, 17, 12, 12, 453299))),
            ],
        ),
    ]
