# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-22 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Validateapp', '0002_auto_20180922_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reg',
            name='password2',
            field=models.CharField(max_length=255),
        ),
    ]
