# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-22 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Validateapp', '0004_auto_20180922_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
